---
fullname: Reduction Effects
shortname: reduction-effects
organization: coq-community
community: true
action: true

synopsis: A Coq plugin to add reduction side effects to some Coq reduction strategies

authors:
- name: Hugo Herbelin
  initial: true

maintainers:
- name: Yishuai Li
  nickname: liyishuai
- name: Jason Gross
  nickname: JasonGross

opam-file-maintainer: "Yishuai Li <yishuai@cis.upenn.edu>"

license:
  fullname: Mozilla Public License 2.0
  identifier: MPL-2.0

plugin: true

supported_coq_versions:
  text: Coq 8.10 or later
  opam: '{ >= "8.10" }'

tested_coq_opam_versions:
- version: '8.10'
- version: '8.11'
- version: '8.12'
- version: '8.13'
- version: '8.14'
- version: '8.15'
- version: '8.16'
- version: '8.17'
- version: '8.18.
- version: 'dev'

dependencies:
  - description: '[Cppo](https://github.com/ocaml-community/cppo)'
    opam:
      name: cppo
      version: '{ >= "1.6.8" }'
test_target: test
ci_extra_dev: true

namespace: ReductionEffect
